all:
  children:
    vpn_nodes:
      children:
        opengater_nodes:
          hosts:
            node-test:
              ansible_host: 89.124.79.66
            #node-nl-01:
              #ansible_host: 140.99.223.126
        #unfence_nodes:
          #hosts: {}
    #infra:
      #hosts:
        #panel:
          #ansible_host: panel.duckpunch.cc
